
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name":"Astrodev",
    "email": "astrodev@labenu.com",
    "password": "astrodev123"
}

###


POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@Labenu.com",
    "password": "astrodev123"
}

###


POST http://localhost:3003/posts/create
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3MjE5Yzk3LWYxMTctNGVhYi1iZWM4LTlhYjU0NzNkZDJiMSIsImlhdCI6MTY1MTc3MTkyNCwiZXhwIjoxNjUxNzg5OTI0fQ.Nm8lZXvu11KERvMe_5jtEWJBzzk4xDRGjIMgS7XGYRg

{
    "photo": "https://www.quadrorama.com.br/wp-content/uploads/2018/05/quadro-com-foto-imagem-personalizada.png", 
    "description": "Minha Foto",
    "type": "normal"
}

###


GET http://localhost:3003/posts/
Content-Type: application/json
authorization: