POST http://localhost:3003/post
Content-Type: application/json

      {
        "name": "Astro Dev",
        "nickname": "Devinho",
        "email": "Jocas@labenu.com"
      }

###

GET http://localhost:3003/user/1649442954193
Content-Type: application/json

###

PUT http://localhost:3003/user/edit/1649442954193
Content-Type: application/json

{
	"name": "Roberto",
  "nickname": "Junior"
}

###

POST http://localhost:3003/task
Content-Type: application/json

{
	"title": "Criar banco dos alunos",
	"description": "Devemos criar o banco dos alunos para o módulo do backend",
	"limitDate": "04/05/2020",
	"creatorUserId": "1649442954193"
}

###

GET http://localhost:3003/task/1649527499614
Content-Type: application/json